//
// Created by Frixs on 7.10.2018.
//

#define PLAYER_COUNT 2
#define GOAL_DEFAULT 3
#define TIMEOUT_LOST_CONN 120
#define TIMEOUT_UNSUCCESSFUL 5
#define MAX_CLIENT_TOKENS 5
#define PORT_DEFAULT 10000
#define CUSTOM_PORT_LOWEST_POSSIBLE 1
#define CUSTOM_PORT_HIGHEST_POSSIBLE 65535
#define ANSI_COLOR_BLUE "\x1b[34m"
#define ANSI_COLOR_CYAN "\x1b[36m"
#define ANSI_COLOR_RESET "\x1b[0m"

#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

#endif //SERVER_CONSTANTS_H
