//
// Created by Frixs on 7.10.2018.
//

#define PLAYER_COUNT 2
#define MAX_TOKENS 5
#define DEFAULT_PORT 10000
#define CUSTOM_PORT_LOWEST_POSSIBLE 1
#define CUSTOM_PORT_HIGHEST_POSSIBLE 65535

#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

#endif //SERVER_CONSTANTS_H
